/**
 * Style Dictionary Configuration — Pluto Design System
 *
 * Transforms DTCG-format design tokens into:
 *   1. CSS custom properties  → dist/css/tokens.css (consumed by web apps)
 *   2. TypeScript constants   → dist/js/tokens.ts  (type-safe token access in React)
 *   3. JSON flat map          → dist/json/tokens.json (tooling, AI metadata)
 *   4. Figma-ready JSON       → dist/figma/tokens.json (Figma Variables sync)
 *
 * Why Style Dictionary v4?
 *   - Native DTCG ($value/$type) support without manual transforms
 *   - ESM-first, Node 20 compatible
 *   - Composable transform groups
 */

import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

// Register Tokens Studio transforms for Figma Variable compatibility
register(StyleDictionary);

// ─── Custom Transforms ────────────────────────────────────────────────────────

/**
 * Converts DTCG token path to CSS custom property name.
 * e.g. color.neutral.900 → --pluto-color-neutral-900
 * e.g. space.component.padding-md → --pluto-space-component-padding-md
 */
StyleDictionary.registerTransform({
  name: 'pluto/name/css',
  type: 'name',
  transform: (token) => {
    return `pluto-${token.path.join('-').replace(/\./g, '-')}`;
  },
});

/**
 * Converts DTCG token path to camelCase JS identifier.
 * e.g. color.neutral.900 → colorNeutral900
 */
StyleDictionary.registerTransform({
  name: 'pluto/name/js',
  type: 'name',
  transform: (token) => {
    return token.path
      .map((part, i) =>
        i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
      )
      .join('')
      .replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  },
});

/**
 * Shadow tokens: converts Style Dictionary shadow object → CSS box-shadow string.
 * Supports both single shadow (object) and multi-layer shadows (array).
 */
StyleDictionary.registerTransform({
  name: 'pluto/shadow/css',
  type: 'value',
  filter: (token) => token.$type === 'shadow' || token.type === 'boxShadow',
  transform: (token) => {
    const toShadowStr = (s) => {
      if (!s || s === 'none') return 'none';
      const inset = s.inset ? 'inset ' : '';
      return `${inset}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`;
    };
    const val = token.$value ?? token.value;
    if (Array.isArray(val)) return val.map(toShadowStr).join(', ');
    if (typeof val === 'string') return val;
    return toShadowStr(val);
  },
});

/**
 * cubicBezier tokens: [x1,y1,x2,y2] array → cubic-bezier(x1, y1, x2, y2) string.
 */
StyleDictionary.registerTransform({
  name: 'pluto/cubicBezier/css',
  type: 'value',
  filter: (token) => token.$type === 'cubicBezier',
  transform: (token) => {
    const val = token.$value ?? token.value;
    if (Array.isArray(val)) return `cubic-bezier(${val.join(', ')})`;
    return val;
  },
});

// ─── Custom Format: TypeScript Token Map ─────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'pluto/typescript/tokens',
  format: ({ dictionary }) => {
    const lines = [
      `// Auto-generated by Style Dictionary — DO NOT EDIT`,
      `// Source: packages/tokens/src`,
      ``,
      `export const tokens = {`,
    ];

    dictionary.allTokens.forEach((token) => {
      const key = token.name;
      const val = typeof token.value === 'string'
        ? `'${token.value}'`
        : JSON.stringify(token.value);
      const desc = token.$description || token.description || '';
      if (desc) lines.push(`  /** ${desc} */`);
      lines.push(`  '${key}': ${val},`);
    });

    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type TokenName = keyof typeof tokens;`);
    lines.push(`export type TokenValue = (typeof tokens)[TokenName];`);

    return lines.join('\n');
  },
});

// ─── Custom Format: Figma Variables JSON ─────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'pluto/figma/variables',
  format: ({ dictionary }) => {
    const figmaTokens = {};

    dictionary.allTokens.forEach((token) => {
      const group = token.path.slice(0, -1).join('/');
      const name = token.path[token.path.length - 1];

      if (!figmaTokens[group]) figmaTokens[group] = {};
      figmaTokens[group][name] = {
        $value: token.value,
        $type: token.$type || token.type,
        $description: token.$description || token.description || '',
        $extensions: {
          'com.pluto.path': token.path.join('.'),
          'com.pluto.tier': token.path[0] === 'color' ? 'primitive' : 'semantic',
        },
      };
    });

    return JSON.stringify({ global: figmaTokens }, null, 2);
  },
});

// ─── Transform Groups ─────────────────────────────────────────────────────────

StyleDictionary.registerTransformGroup({
  name: 'pluto/css',
  transforms: [
    'attribute/cti',
    'pluto/name/css',
    'pluto/shadow/css',
    'pluto/cubicBezier/css',
    'ts/size/px',
    'ts/color/modifiers',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'pluto/js',
  transforms: [
    'attribute/cti',
    'pluto/name/js',
    'pluto/shadow/css',
    'pluto/cubicBezier/css',
    'ts/size/px',
  ],
});

// ─── Build Configuration ──────────────────────────────────────────────────────

const primitivesSources = [
  'src/primitives/color.json',
  'src/primitives/typography.json',
  'src/primitives/spacing.json',
  'src/primitives/radius.json',
  'src/primitives/elevation.json',
  'src/primitives/motion.json',
  'src/primitives/breakpoints.json',
];

const semanticSources = [
  ...primitivesSources,
  'src/semantic/color.json',
  'src/semantic/typography.json',
  'src/semantic/spacing.json',
];

const configs = [
  // ── 1. Primitive CSS variables (used for Figma token export) ──
  {
    log: { warnings: 'warn' },
    source: primitivesSources,
    preprocessors: ['tokens-studio'],
    platforms: {
      css: {
        transformGroup: 'pluto/css',
        prefix: 'pluto',
        buildPath: 'dist/css/',
        files: [
          {
            destination: 'primitives.css',
            format: 'css/variables',
            options: {
              outputReferences: false,
              selector: ':root',
              fileHeader: () => [
                'Pluto Design System — Primitive Tokens',
                'Do not use these directly in components. Use semantic tokens.',
              ],
            },
          },
        ],
      },
      json: {
        transformGroup: 'pluto/js',
        buildPath: 'dist/json/',
        files: [
          {
            destination: 'primitives.json',
            format: 'json/nested',
          },
        ],
      },
    },
  },

  // ── 2. Semantic CSS variables (light theme = default) ──
  {
    log: { warnings: 'warn' },
    source: [...semanticSources, 'src/themes/light.json'],
    preprocessors: ['tokens-studio'],
    platforms: {
      css: {
        transformGroup: 'pluto/css',
        prefix: 'pluto',
        buildPath: 'dist/css/',
        files: [
          {
            destination: 'tokens.css',
            format: 'css/variables',
            options: {
              outputReferences: true,
              selector: ':root, [data-theme="light"]',
              fileHeader: () => [
                'Pluto Design System — Full Token Set (Light Theme default)',
                'Import this file once at the root of your application.',
              ],
            },
          },
        ],
      },
      js: {
        transformGroup: 'pluto/js',
        buildPath: 'dist/js/',
        files: [
          {
            destination: 'tokens.ts',
            format: 'pluto/typescript/tokens',
          },
        ],
      },
      json: {
        transformGroup: 'pluto/js',
        buildPath: 'dist/json/',
        files: [
          {
            destination: 'tokens.json',
            format: 'json/flat',
          },
        ],
      },
      figma: {
        transformGroup: 'pluto/js',
        buildPath: 'dist/figma/',
        files: [
          {
            destination: 'tokens.json',
            format: 'pluto/figma/variables',
          },
        ],
      },
    },
  },

  // ── 3. Dark theme override CSS ──
  {
    log: { warnings: 'warn' },
    source: [...semanticSources, 'src/themes/dark.json'],
    preprocessors: ['tokens-studio'],
    platforms: {
      css: {
        transformGroup: 'pluto/css',
        prefix: 'pluto',
        buildPath: 'dist/css/themes/',
        files: [
          {
            destination: 'dark.css',
            format: 'css/variables',
            options: {
              outputReferences: true,
              selector: '[data-theme="dark"]',
              fileHeader: () => ['Pluto Design System — Dark Theme'],
            },
            filter: (token) => token.path[0] === 'theme',
          },
        ],
      },
    },
  },

  // ── 4. High-contrast theme override CSS ──
  {
    log: { warnings: 'warn' },
    source: [...semanticSources, 'src/themes/high-contrast.json'],
    preprocessors: ['tokens-studio'],
    platforms: {
      css: {
        transformGroup: 'pluto/css',
        prefix: 'pluto',
        buildPath: 'dist/css/themes/',
        files: [
          {
            destination: 'high-contrast.css',
            format: 'css/variables',
            options: {
              outputReferences: false,
              selector: '[data-theme="high-contrast"], @media (prefers-contrast: more)',
              fileHeader: () => ['Pluto Design System — High Contrast Theme (WCAG AAA)'],
            },
            filter: (token) => token.path[0] === 'theme',
          },
        ],
      },
    },
  },
];

// Run all builds
for (const config of configs) {
  const sd = new StyleDictionary(config);
  await sd.buildAllPlatforms();
}

console.log('\n✅ Pluto token build complete.\n');
